### ISSUE TITLE
Proposal to introduce webmention verification logic as a function

### ISSUE THREAD

**Issue by capjamesg** [capjamesg/indieweb-utils#7]
The [webmention specification](https://www.w3.org/TR/webmention/#webmention-verification) outlines a series of steps that must be completed to validate a webmention, as seen in the "Request Validation" and "Webmention Verification" sections of the spec.

I wonder if it would be worth introducing logic that completes the webmention verification stage. This code would return errors compliant with the specification if any are encountered during validation.

My reservation is that some areas of the spec, such as how to limit redirects and request sizes, are up to individual implements. As such, it might be appropriate to include flags that can change values or checks that are not directly mentioned in the spec.

Implementing webmention validation would make it easy for anyone to start creating their own webmention endpoint with the library without having to fully understand the ins-and-outs of the spec and validation.

**Comment by jamesvandyne** [comment]
Yes - I think it makes sense to add a `webmentions.verify_webmention` type of function. What would the input be? `target_url` and `webmention_source_url`? 

In regards to request sizes / redirects etc.. we can just pick some sane defaults and it should be fine. We could allow some (or all?) of the defaults to be overridden when called with a kwarg if we choose.

Since it's validation, perhaps it should just raise if there's an issue and return None if everything's fine.

```python
def verify_webmention(*, target_url: str, webmention_source_url: str) -> None:
    # do some validation 
    # Oh no, we ran into an error
    raise TargetUrlNotFound()
```

**Comment by capjamesg** [comment]
I have added this functionality in PR #19.
